# python3 -m experiments.experiment1 --device 1 --relative_coords --no-pen_state --no-stroke_embedding --no-sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run1/ --results_path ./results/experiment1/run1.pkl
# python3 -m experiments.experiment1 --device 1 --relative_coords --pen_state --no-stroke_embedding --no-sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run2/ --results_path ./results/experiment1/run2.pkl
# python3 -m experiments.experiment1 --device 1 --relative_coords --no-pen_state --stroke_embedding --no-sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run3/ --results_path ./results/experiment1/run3.pkl
# python3 -m experiments.experiment1 --device 1 --relative_coords --no-pen_state --no-stroke_embedding --sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run4/ --results_path ./results/experiment1/run4.pkl
# python3 -m experiments.experiment1 --device 1 --relative_coords --no-pen_state --no-stroke_embedding --no-sketch_pos --stroke_pos --ckpt_path ./checkpoints/experiment1/run5/ --results_path ./results/experiment1/run5.pkl
# python3 -m experiments.experiment1 --device 1 --relative_coords --pen_state --no-stroke_embedding --sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run6/ --results_path ./results/experiment1/run6.pkl
# python3 -m experiments.experiment1 --device 1 --relative_coords --pen_state --no-stroke_embedding --no-sketch_pos --stroke_pos --ckpt_path ./checkpoints/experiment1/run7/ --results_path ./results/experiment1/run7.pkl
# python3 -m experiments.experiment1 --device 1 --relative_coords --no-pen_state --stroke_embedding --sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run8/ --results_path ./results/experiment1/run8.pkl
# python3 -m experiments.experiment1 --device 1 --relative_coords --no-pen_state --stroke_embedding --no-sketch_pos --stroke_pos --ckpt_path ./checkpoints/experiment1/run9/ --results_path ./results/experiment1/run9.pkl

# python3 -m experiments.experiment1 --device 1 --no-relative_coords --no-pen_state --no-stroke_embedding --no-sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run10/ --results_path ./results/experiment1/run10.pkl
# python3 -m experiments.experiment1 --device 1 --no-relative_coords --pen_state --no-stroke_embedding --no-sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run11/ --results_path ./results/experiment1/run11.pkl
# python3 -m experiments.experiment1 --device 1 --no-relative_coords --no-pen_state --stroke_embedding --no-sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run12/ --results_path ./results/experiment1/run12.pkl
# python3 -m experiments.experiment1 --device 1 --no-relative_coords --no-pen_state --no-stroke_embedding --sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run13/ --results_path ./results/experiment1/run13.pkl
# python3 -m experiments.experiment1 --device 1 --no-relative_coords --no-pen_state --no-stroke_embedding --no-sketch_pos --stroke_pos --ckpt_path ./checkpoints/experiment1/run14/ --results_path ./results/experiment1/run14.pkl
# python3 -m experiments.experiment1 --device 1 --no-relative_coords --pen_state --no-stroke_embedding --sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run15/ --results_path ./results/experiment1/run15.pkl
# python3 -m experiments.experiment1 --device 1 --no-relative_coords --pen_state --no-stroke_embedding --no-sketch_pos --stroke_pos --ckpt_path ./checkpoints/experiment1/run16/ --results_path ./results/experiment1/run16.pkl
# python3 -m experiments.experiment1 --device 1 --no-relative_coords --no-pen_state --stroke_embedding --sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run17/ --results_path ./results/experiment1/run17.pkl
# python3 -m experiments.experiment1 --device 1 --no-relative_coords --no-pen_state --stroke_embedding --no-sketch_pos --stroke_pos --ckpt_path ./checkpoints/experiment1/run18/ --results_path ./results/experiment1/run18.pkl

# CHARMANDER
python3 -m experiments.experiment1 --device 0 --relative_coords --no-pen_state --no-stroke_embedding --no-sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run1/ --results_path ./results/experiment1/run1.pkl
python3 -m experiments.experiment1 --device 0 --no-relative_coords --no-pen_state --no-stroke_embedding --no-sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run10/ --results_path ./results/experiment1/run10.pkl
python3 -m experiments.experiment1 --device 0 --relative_coords --pen_state --no-stroke_embedding --no-sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run2/ --results_path ./results/experiment1/run2.pkl
python3 -m experiments.experiment1 --device 0 --no-relative_coords --pen_state --no-stroke_embedding --no-sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run11/ --results_path ./results/experiment1/run11.pkl
python3 -m experiments.experiment1 --device 0 --relative_coords --no-pen_state --stroke_embedding --no-sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run3/ --results_path ./results/experiment1/run3.pkl
python3 -m experiments.experiment1 --device 0 --no-relative_coords --no-pen_state --stroke_embedding --no-sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run12/ --results_path ./results/experiment1/run12.pkl
python3 -m experiments.experiment1 --device 0 --relative_coords --no-pen_state --no-stroke_embedding --sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run4/ --results_path ./results/experiment1/run4.pkl
python3 -m experiments.experiment1 --device 0 --no-relative_coords --no-pen_state --no-stroke_embedding --sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run13/ --results_path ./results/experiment1/run13.pkl
python3 -m experiments.experiment1 --device 0 --relative_coords --no-pen_state --no-stroke_embedding --no-sketch_pos --stroke_pos --ckpt_path ./checkpoints/experiment1/run5/ --results_path ./results/experiment1/run5.pkl
python3 -m experiments.experiment1 --device 0 --no-relative_coords --no-pen_state --no-stroke_embedding --no-sketch_pos --stroke_pos --ckpt_path ./checkpoints/experiment1/run14/ --results_path ./results/experiment1/run14.pkl

# PIKACHU 
python3 -m experiments.experiment1 --device 1 --relative_coords --pen_state --no-stroke_embedding --sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run6/ --results_path ./results/experiment1/run6.pkl
python3 -m experiments.experiment1 --device 1 --no-relative_coords --pen_state --no-stroke_embedding --sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run15/ --results_path ./results/experiment1/run15.pkl
python3 -m experiments.experiment1 --device 1 --relative_coords --pen_state --no-stroke_embedding --no-sketch_pos --stroke_pos --ckpt_path ./checkpoints/experiment1/run7/ --results_path ./results/experiment1/run7.pkl
python3 -m experiments.experiment1 --device 1 --no-relative_coords --pen_state --no-stroke_embedding --no-sketch_pos --stroke_pos --ckpt_path ./checkpoints/experiment1/run16/ --results_path ./results/experiment1/run16.pkl
python3 -m experiments.experiment1 --device 1 --relative_coords --no-pen_state --stroke_embedding --sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run8/ --results_path ./results/experiment1/run8.pkl
python3 -m experiments.experiment1 --device 1 --no-relative_coords --no-pen_state --stroke_embedding --sketch_pos --no-stroke_pos --ckpt_path ./checkpoints/experiment1/run17/ --results_path ./results/experiment1/run17.pkl
python3 -m experiments.experiment1 --device 1 --relative_coords --no-pen_state --stroke_embedding --no-sketch_pos --stroke_pos --ckpt_path ./checkpoints/experiment1/run9/ --results_path ./results/experiment1/run9.pkl
python3 -m experiments.experiment1 --device 1 --no-relative_coords --no-pen_state --stroke_embedding --no-sketch_pos --stroke_pos --ckpt_path ./checkpoints/experiment1/run18/ --results_path ./results/experiment1/run18.pkl